application: dovetail-data-1
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /favicon.ico
  static_files: pages/favicon.ico
  upload: pages/favicon\.ico
  
- url: /api.html
  static_files: api.html
  upload: api\.html

- url: /p
  static_dir: pages
  
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: ssl
  version: latest
 
- name: jinja2
  version: latest
  
- name: PIL
  version: latest
  
- name: matplotlib
  version: latest
  
- name: numpy
  version: latest
  